theme: jekyll-theme-minimal

title: paperx123
description: AI engineering, agentic systems, and software engineering

author:
  name: paperx123

url: "https://paperx123.github.io"
baseurl: ""

github_username: paperx123

# Optional
show_downloads: false
